# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    name: Pytest passing tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pytest Action Step
        id: pytest
        uses: paolorechia/fast-pytest-github-action@develop
        with:
          pytest_args: 'sample_py/test_success.py'
          requirements_file: 'test_requirements.txt'
